version: 2
jobs:
  # publish jobs require $DOCKERHUB_REPO, $DOCKERHUB_USER, $DOCKERHUB_PASS defined
  publish_docker_linuxamd64:
    machine:
      enabled: true
    steps:
      - checkout  
      - run:
          command: |
            LATEST_TAG=${CIRCLE_TAG:1} #trim v from tag
            #
            sudo docker build --pull -t $DOCKERHUB_REPO:$LATEST_TAG -f Dockerfile .
            sudo docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS
            sudo docker push $DOCKERHUB_REPO:$LATEST_TAG

workflows:
  version: 2
  publish:
    jobs:
      - publish_docker_linuxamd64:
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /v.+/